{
 "title": "Multichain Monitor",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Bridge Volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bridge_monitor_bridge_volume{token=\"0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48\"} / 1000000",
     "legendFormat": "USDC Volume"
    },
    {
     "expr": "bridge_monitor_bridge_volume{token=\"eth\", direction=\"l1-to-l2\"} / 1000000000000000000",
     "legendFormat": "ETH Volume"
    }
   ]
  },
  {
   "title": "ERC20 Bridge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "bridge_monitor_l1_erc_20_bridge_initiated",
     "legendFormat": "ERC20 Bridge Initiated {{localToken}}"
    },
    {
     "expr": "bridge_monitor_l2_erc_20_bridge_finalized",
     "legendFormat": "ERC20 Bridge Finalized {{remoteToken}}"
    }
   ]
  },
  {
   "title": "Native Bridge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "bridge_monitor_l1_eth_bridge_initiated",
     "legendFormat": "Native Bridge Initiated"
    },
    {
     "expr": "bridge_monitor_l2_eth_bridge_finalized",
     "legendFormat": "Native Bridge Finalized"
    }
   ]
  }
 ]
}